### PR TITLE
[feat] Scale the weight init in the MHA projections when same dimensions all around

### PR DESCRIPTION
**Pull request by blefaudeux**
## What does this PR do?
Opportunistic, I was refactoring the projections in https://github.com/facebookresearch/xformers/pull/178 and spotted this difference. I'm not sure whether it's something which would have affected some of your tests @dianaml0 ?
Scale the weights by 1/sqrt(2) when KQV have the same dimensions, same as [fairseq](https://github.com/pytorch/fairseq/blob/cf8ff8c3c5242e6e71e8feb40de45dd699f3cc08/fairseq/modules/multihead_attention.py#L99)

## Before submitting

- [x] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [x] Did you make sure to update the docs?
  - [ ] N/A
- [x] Did you write any new necessary tests?
  - [ ] N/A
- [x] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/master/CHANGELOG.md)? (if needed)
  - [ ] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by blefaudeux** [comment]
empirical testing: there's indeed a difference at the very beginning of the training, in this specific case (not too big model) the difference does not stay really, but trusting fairseq that this is the better thing to do
 
Screenshot from 2022-01-13 19-47-25

**Comment by blefaudeux** [comment]
cc @suchenzang if you have a back story around that ?

**Review by dianaml0 — APPROVED** [review]
Interesting this is a useful detail! Could have affected my training indeed

**Comment by jieru-hu** [comment]
@blefaudeux would it be possible to share how you generated the empirical testing graph? is the script available in the repo? (this seems like a useful thing for other contributors to run as well :) )

**Comment by blefaudeux** [comment]
> @blefaudeux would it be possible to share how you generated the empirical testing graph? is the script available in the repo? (this seems like a useful thing for other contributors to run as well :) )

that's just microGPT, an epoch is about 30 minutes on my laptop and you can check with the sample prediction (pseudo shakespeare) whether it all makes sense, which is a useful sanity check I think (same with the Compositional PR)

**Pull request merged**
