### PR TITLE
[feature] Embedding weight tying (#169)

### PR DESCRIPTION
**Pull request by blefaudeux**
## What does this PR do?
Tentative implementation of #169, fairly minor, with a matching unit test update.
 cc @erip  
[See](https://arxiv.org/pdf/1608.05859v3.pdf) for a reference and more context

## Before submitting

- [x] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/fairscale/blob/master/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [x] Did you make sure to update the docs?
  - [ ] N/A
- [x] Did you write any new necessary tests?
  - [ ] N/A
- [x] Did you update the [changelog](https://github.com/facebookresearch/fairscale/blob/master/CHANGELOG.md)? (if needed)
  - [ ] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by erip** [comment]
Looks good! I can pull in the changes to my project using xformers and try it out.

**Comment by erip** [comment]
Looks like there's a tiny bit of performance improvement (on my silly CPU machine):

```sh
➜  python train.py tie
Epoch 1 step: 1 Loss: 9.666109 Took 5.800530 seconds. bsz (toks): 2438
Epoch 1 step: 2 Loss: 8.875856 Took 15.910649 seconds. bsz (toks): 3595
Epoch 1 step: 3 Loss: 7.488206 Took 15.342067 seconds. bsz (toks): 3866
^C
...
➜  python train.py
Epoch 1 step: 1 Loss: 9.688322 Took 5.884865 seconds. bsz (toks): 2438
Epoch 1 step: 2 Loss: 8.820903 Took 16.065957 seconds. bsz (toks): 3595
Epoch 1 step: 3 Loss: 7.255448 Took 15.518760 seconds. bsz (toks): 3866
```

I think this is generally the right direction. I can also take a look at comparisons of memory util between them, too.

**Comment by blefaudeux** [comment]
> Looks like there's a tiny bit of performance improvement (on my silly CPU machine):
> 
> ```shell
> ➜  python train.py tie
> Epoch 1 step: 1 Loss: 9.666109 Took 5.800530 seconds. bsz (toks): 2438
> Epoch 1 step: 2 Loss: 8.875856 Took 15.910649 seconds. bsz (toks): 3595
> Epoch 1 step: 3 Loss: 7.488206 Took 15.342067 seconds. bsz (toks): 3866
> ^C
> ...
> ➜  python train.py
> Epoch 1 step: 1 Loss: 9.688322 Took 5.884865 seconds. bsz (toks): 2438
> Epoch 1 step: 2 Loss: 8.820903 Took 16.065957 seconds. bsz (toks): 3595
> Epoch 1 step: 3 Loss: 7.255448 Took 15.518760 seconds. bsz (toks): 3866
> ```
> 
> I think this is generally the right direction. I can also take a look at comparisons of memory util between them, too. That said, printing out the number of trainable parameters shows that this seems to work well:
> 
> ```
> Tied: There are 25,588,799 trainable parameters.
> Untied: There are 33,359,807 trainable parameters.
> ```

would you have a small enough task in mind ? It could be added to the examples and can be useful for sanity checking and perf regression catching.

**Comment by erip** [comment]
This example is pretty involved ([machine translation](https://erip.github.io/posts/2022/01/nmt_with_xformers_pt1/)), but I could probably make something smaller.

**Comment by blefaudeux** [comment]
> This example is somewhat involved ([machine translation](https://erip.github.io/posts/2022/01/nmt_with_xformers_pt1/)), but I could probably make something smaller. If that's of interest, I'm happy to try to contribute something!

just if it's not too much work ! There are two examples [here](https://github.com/facebookresearch/xformers/tree/main/examples) if that helps. Also, you'll really need a GPU at some point :D

**Review by dianaml0 — APPROVED** [review]
LGTM!

**Pull request merged**
