### PR TITLE
Publish Wheels to PyPi

### PR DESCRIPTION
**Pull request by AbdBarho**
Related #533 #573 #532  #534 #523 #473 (damn, this is getting out of hand).

A few decisions here:
* We only upload the wheels built against the latest torch version (1.13) with latest cuda (11.7)
* the combination 1.13 and 11.6 was removed with the hope that the other version compensates.
* The 1.12 version is left in for users who still haven't updated yet, but it is not uploaded to pypi.
* the version string is as discussed in https://github.com/facebookresearch/xformers/issues/533#issuecomment-1348736095
  * _release candidate_ with a suffix `dev` (not `rc`) to stay consistent with conda
  * we should probably consolidate the version generation to one place

Example run:
https://github.com/AbdBarho/xformers-wheels/actions/runs/3689261975

Published Wheels:
https://test.pypi.org/project/formers/0.0.15.dev376/#files

TODO (for future PRs):
* Publish on tagged commits
* Create source distribution

### CODE REVIEW

**Review by danthe3rd — COMMENTED** [review]
This looks great! Thanks a lot for putting this together!
Just requested a minor change in the version numbering

**Comment by danthe3rd** [comment]
Also we should probably also have a source-distribution, but we can worry about that later

**Comment by AbdBarho** [comment]
@danthe3rd I have added the requested changes.

Example Publish:
https://test.pypi.org/project/formers/0.0.15rc380/

**Comment by danthe3rd** [comment]
> @danthe3rd I have added the requested changes.
> 
> Example Publish: https://test.pypi.org/project/formers/0.0.15rc380/

Thanks! Just a last thing - it should be a release candidate for the next version (0.0.16rcXXX here)

**Comment by AbdBarho** [comment]
@danthe3rd so do you mean I should update the `version.txt` or when computing the version string increment the patch by 1?

**Comment by AbdBarho** [comment]
@danthe3rd I took the easiest path and wrote a python script that generates the version. I didn't want to hack around with bash.

https://test.pypi.org/project/formers/0.0.16rc385/

**Comment by danthe3rd** [comment]
Let's merge :)
Thanks a lot for the contribution @AbdBarho ! let's see if the credentials are correctly configured now

**Pull request merged**
