### PR TITLE
[refactor] Update to a more recent flash-attention version

### LINKED ISSUE #1159: Incompatibility Between xformers FA3 Torch Custom op Wrapper and recent `flashattn_hopper_cuda`
There is an incompatibility between xformers FA3 Torch custom op wrapper logic and recent `flashattn_hopper_cuda` changes, resulting in a `TypeError` due to changes in required arguments for the `fwd()` function:

```
TypeError: fwd(): incompatible function arguments. The following argument types are supported:
  1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: torch.Tensor, arg3: Optional[torch.Tensor], arg4: float, arg5: Optional[torch.Tensor], arg6: Optional[torch.Tensor], arg7: Optional[torch.Tensor], arg8: bool, arg9: int, arg10: int) -> list[torch.Tensor]
```

The recent FA3 requires the positional arguments `window_size_left` and `window_size_right` (see [source](https://github.com/Dao-AILab/flash-attention/blob/main/hopper/flash_api.cpp#L463-L475)).

Me and my colleague @antferdom encountered this issue while attempting to use our own installed FA3 due to failure in compiling FA3 within xformers. As a result, we made modifications to `mha_fwd` to use FA3 as a fallback.

```python
def mha_fwd(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    cu_seqlens_q: torch.Tensor,
    cu_seqlens_k: torch.Tensor,
    seqused_k: torch.Tensor,
    max_seqlen_q: int,
    max_seqlen_k: int,
    p: float,
    softmax_scale: float,
    is_causal: bool,
) -> Tuple[torch.Tensor, torch.Tensor]:
    if cu_seqlens_q is None:
        assert cu_seqlens_k is None
        assert seqused_k is None
        window_size_left = -1
        window_size_right = 0 if is_causal else -1
        (
            out,
            q_padded,
            k_padded,
            v_padded,
            out_padded,
            softmax_lse,
            p,
        ) = _C_flashattention3.fwd(
            query, key, value, None, softmax_scale, None, None, None, is_causal,
            window_size_left, window_size_right, False,
        )
```

So, we suggest updating `mha_fwd` to properly account for `window_size_left` and `window_size_right` as required positional arguments, or adding a check in `_C_flashattention3.fwd` to determine if these arguments are needed to support all versions of FA3.

If this solution is acceptable, we would be happy to submit a Pull Request to address this issue.

### PR DESCRIPTION
**Pull request by ohwi**
## What does this PR do?
Fixes #1159 .

With @antferdom, ran tests and benchmarks. Here is the result of `benchmark_mem_eff_attention.py`:
https://docs.google.com/spreadsheets/d/1dxEBXmhfmpLVz8mvIXGg1fGy-JjjjX-EDn-xtjVupnU/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1T85zCaTSSBx1xslQJ14I6VpfipkONsPb83CRXjpn1r0/edit?usp=sharing

## Before submitting

- [x] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [ ] N/A
- [ ] Did you make sure to update the docs?
  - [x] N/A
- [ ] Did you write any new necessary tests?
  - [x] N/A
- [ ] Did you update the [changelog](https://github.com/facebookresearch/xformers/blob/master/CHANGELOG.md)? (if needed)
  - [x] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by lw** [comment]
In https://github.com/facebookresearch/xformers/commit/839c4ec4b928f1f02f83d25a7d111bde819e6bce we updated FlashAttention to version 2.7.2, is this PR still relevant?

**Comment by lw** [comment]
@danthe3rd could you take a look?

**Comment by danthe3rd** [comment]
I believe the value of `win_right` does not matter, as it is set within the function anyway there:
https://github.com/Dao-AILab/flash-attention/blob/0dfb28174333d9eefb7c1dd4292690a8458d1e89/hopper/flash_api.cpp#L551

**Comment by ohwi** [comment]
You’re right—I missed that point. Thank you for pointing it out!

**Pull request closed without merging**
