### PR TITLE
Handle CUDA 12.1 correctly in setup

### PR DESCRIPTION
**Pull request by arvindsun**
## What does this PR do?
Fixes Cuda 12.1 detection while building from source.

## Before submitting

- [x] Did you have fun?
  - Make sure you had fun coding 🙃
- [x] Did you read the [contributor guideline](https://github.com/facebookresearch/xformers/blob/master/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
  - [x] N/A
- [x] Did you make sure to update the docs?
  - [x] N/A
- [x] Did you write any new necessary tests?
  - [x] N/A
- [x] Did you update the [changelog](https://github.com/facebookresearch/xformers/blob/master/CHANGELOG.md)? (if needed)
  - [x] N/A

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by danthe3rd** [comment]
Hi,
Thanks for your PR! Can you also include the output of "nvcc -V" which caused the issue? I've been building xformers with cuda 12.1 from source for some time and it worked fine...

**Comment by arvindsun** [comment]
> Hi, Thanks for your PR! Can you also include the output of "nvcc -V" which caused the issue? I've been building xformers with cuda 12.1 from source for some time and it worked fine...

nvcc output that was causing the issue: 
```
# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

As you can see `release[1][0]` had the value `1,`  in this case.

**Comment by arvindsun** [comment]
> > ```
> > # nvcc -V
> > nvcc: NVIDIA (R) Cuda compiler driver
> > Copyright (c) 2005-2023 NVIDIA Corporation
> > Built on Mon_Apr__3_17:16:06_PDT_2023
> > Cuda compilation tools, release 12.1, V12.1.105
> > Build cuda_12.1.r12.1/compiler.32688072_0
> > ```
> 
> The function should return `1201` in that case. I believe this was correct before, but with your code it would return `121`, which is not what we want.
> 
> ```python
> release = "12.1,"
> print(int(''.join(filter(str.isdigit, release))))
> # 121
> ```

That is precisely the behavior I was changing! 1201 == cuda version 12.01 and 121 == cuda version 12.1 - otherwise we get GPU mismatches.

**Comment by arvindsun** [comment]
> > 1201 == cuda version 12.01 and 121 == cuda version 12.1
> 
> I don't understand, this should be the same version..? What errors were you hitting? This version computed in `setup.py` is only used in a few locations:
> 
> https://github.com/facebookresearch/xformers/blob/fbf349a23a9e909863c191430bd15d5199dda14b/setup.py#L123-L132
> 
> 
> https://github.com/facebookresearch/xformers/blob/fbf349a23a9e909863c191430bd15d5199dda14b/setup.py#L150
> 
> 
> (where we expect the format to be 1201 and not 121)
> It's also used to provide a better error message in case we can't load the library:
> https://github.com/facebookresearch/xformers/blob/fbf349a23a9e909863c191430bd15d5199dda14b/xformers/_cpp_lib.py#L65-L67
> 
> 
> but none of this should cause any error

If we compile on a machine with cuda 12.1 installed (this is different than cuda 12.01), we see a version mismatch and crashes downstream for extensions not being loaded. IMO the right return value for 12.1 is 121 which will then avoid the errors discussed in https://github.com/facebookresearch/xformers/issues/905

**Comment by danthe3rd** [comment]
> we see a version mismatch and crashes downstream for extensions not being loaded

The cuda version we store at build time is not used for anything that could cause this error ... If you can reproduce this error, we can have a look (you should set `XFORMERS_MORE_DETAILS=1` to get the actual error message).

The change as you propose it currently will disable the build of Flash-Attention on cuda 12.1, because it is only enabled if `cuda_version >= 1100` (https://github.com/facebookresearch/xformers/blob/fbf349a23a9e909863c191430bd15d5199dda14b/setup.py#L134)

**Comment by arvindsun** [comment]
> > > we see a version mismatch and crashes downstream for extensions not being loaded
> > 
> > 
> > The cuda version we store at build time is not used for anything that could cause this error ... If you can reproduce this error, we can have a look (you should set `XFORMERS_MORE_DETAILS=1` to get the actual error message).
> > The change as you propose it currently will disable the build of Flash-Attention on cuda 12.1, because it is only enabled if `cuda_version >= 1100` (
> > https://github.com/facebookresearch/xformers/blob/fbf349a23a9e909863c191430bd15d5199dda14b/setup.py#L134
> > 
> > ).
> > This might make the error disappear, but this is also removing a big part of xFormers at the same time.
> 
> I see that now. Testing with having cuda_version return 1210 - see latest iteration of my PR - still don't know what the root cause of the build error is - will keep you posted.

BTW, do we have a wheel already built with cuda 12.1 and torch 2.1.0?

**Comment by danthe3rd** [comment]
> BTW, do we have a wheel already built with cuda 12.1 and torch 2.1.0?

Yes, you can install it with:
```
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
```

> still don't know what the root cause of the build error is - will keep you posted.

The segmentation fault during build? Yeah we're had it occasionally. For some reason it does not happen in the CI.
But usually updating to CUDA 12.2 (which is compatible with CUDA 12.1) fixes the issue. Actually you only need to update `nvcc`.

**Comment by arvindsun** [comment]
> > BTW, do we have a wheel already built with cuda 12.1 and torch 2.1.0?
> 
> Yes, you can install it with:
> 
> ```
> pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
> ```
> 

Tried that but don't see a cu121 build here: https://download.pytorch.org/whl/xformers/

> > still don't know what the root cause of the build error is - will keep you posted.
> 
> The segmentation fault during build? Yeah we're had it occasionally. For some reason it does not happen in the CI. But usually updating to CUDA 12.2 (which is compatible with CUDA 12.1) fixes the issue. Actually you only need to update `nvcc`.

**Comment by danthe3rd** [comment]
@arvindsun the wheels are in https://download.pytorch.org/whl/cu121/xformers/

**Comment by arvindsun** [comment]
> https://download.pytorch.org/whl/cu121

But if you go here: https://download.pytorch.org/whl/cu121 and click on xformers it links to https://download.pytorch.org/whl/xformers

**Comment by danthe3rd** [comment]
Oh yes this is a bug because the links have relative paths, and apparently
https://download.pytorch.org/whl/cu121
is not the same as
https://download.pytorch.org/whl/cu121/ (<-- Links work now)

**Comment by soulteary** [comment]
It has nothing to do with the version number and does not need to be changed. @danthe3rd 

https://github.com/facebookresearch/xformers/issues/960

**Pull request closed without merging**
