### PR TITLE
add build for Python 3.12

### PR DESCRIPTION
**Pull request by Mon-ius**
updated the CI for conda and wheel build for Python 3.12, as requested in https://github.com/facebookresearch/xformers/issues/1016#issue-2223351721. 🤗

### CODE REVIEW

**Comment by danthe3rd** [comment]
Thanks! Unfortunately the main issue here is that we are running out of storage on anaconda, and won't have space to store extra versions :/
Hopefully we can manage to significatively reduce binary size soon and support all recent python versions

**Comment by Mon-ius** [comment]
Never thought it would be an issue, if that's possible to publish to pypi only?

**Comment by danthe3rd** [comment]
How do you install xFormers? Do you install it with the `--index-url https://download.pytorch.org/whl/cuXXX` part in the pip install command?
If so, we don't have any space problem. We might want to store all Python versions there, and only a limited subset in pypi

**Comment by Mon-ius** [comment]
we have two env setup solutions for xformer installation from `conda` and `pip`, but the `conda` one started not work due to the  version issue, that's why I am here for subimit the PR 🤗

**Comment by danthe3rd** [comment]
conda is usually the better solution, but they also have the lowest storage (~10GB). We were able to [negociate](https://github.com/pypi/support/issues/2907) 20GB for pypi - trying to push it further now.
The only real solution we have is to host on the Meta servers for PyTorch for pip - which are used when you specify `--index-url https://download.pytorch.org/whl/cu121` in pip

**Comment by Mon-ius** [comment]
If it is possible to increase the storage on Conda, that would be ideal. Otherwise, there will always be a compromising solution.

**Comment by danthe3rd** [comment]
I'm working on getting py3.12 support for pip wheels (at least on the PyTorch s3) - hopefully we can enable that soon :)

**Comment by Remember2015** [comment]
any updates?
when I use `pip install xformers --index-url=https://download.pytorch.org/whl/cu121`
it seems not work:
```
Looking in indexes: https://download.pytorch.org/whl/cu121
ERROR: Could not find a version that satisfies the requirement xformers (from versions: none)
ERROR: No matching distribution found for xformers
```

- python=3.12.3
- pytorch=2.3.0 (py3.12_cuda12.1_cudnn8.9.2_0)

**Comment by danthe3rd** [comment]
I didn't get a reply, opened a new issue
https://github.com/pypi/support/issues/4168

**Comment by danthe3rd** [comment]
We have builds for cp12 now, closing

**Pull request closed without merging**
