### PR TITLE
MemEff: BUGFIX when a batch has no keys

### PR DESCRIPTION
**Pull request by danthe3rd**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #492
* #491

### CODE REVIEW

**Review by fmassa — APPROVED** [review]
Thanks!

Can you add a test for this case?

**Comment by danthe3rd** [comment]
Causes some performance regression (about 0.5%) so let's not fix it

**Comment by fmassa** [comment]
@danthe3rd what happens then in this case? Does it raise an error or just yield wrong numbers?

If it yields wrong results, then I think this is a silent but that should be fixed.

**Comment by danthe3rd** [comment]
> @danthe3rd what happens then in this case? Does it raise an error or just yield wrong numbers?
> 
> If it yields wrong results, then I think this is a silent but that should be fixed.

Well I'm not even sure what should happen. If there are some queries but no key/no value, I guess it should be zero?
Currently it either outputs NaN or uninitialized values.

**Pull request closed without merging**
